### PR TITLE
support api_endpoint  for ollama

### PR DESCRIPTION
**Pull request by luixiao0**

### CODE REVIEW

**Comment by luixiao0** [comment]
> This is really awesome thank you!
> 
> What do you think about explicitly adding a `chat_endpoint` and a `generate_endpoint` in the config options for Ollama instead of just `endpoint`? We do this for every other API backend. If a user uses Ollama remotely are we sure they will have chat at `/api/chat` and generate at `/api/generate`?

Adding separate chat_endpoint and generate_endpoint for Ollama isn't necessary because once Ollama is running, it provides both chat and generate functionalities at /api/chat and /api/generate. They are generally available simultaneously. If we were to separate the endpoints in the configuration, it would be more consistent to also separate the model configurations to utilize ollama's multi model management methods(like load a chat model for chat and a FIM model for generate).

**Comment by SilasMarvin** [comment]
If you can make the suggested changes and resolve the merge conflict I will merge it in! Thank you!

**Comment by luixiao0** [comment]
resolved

**Comment by SilasMarvin** [comment]
> resolved, [3a351ff](https://github.com/SilasMarvin/lsp-ai/pull/15/commits/3a351ff4a0ed846ceb4bc9d926ac422c8324a8a1)[237f4cf](https://github.com/SilasMarvin/lsp-ai/commit/237f4cf179b79f74b4ad2e169e8e4f855f96a6b4)

Awesome thank you. If you can implement the changes I suggested above I will merge it

**Comment by luixiao0** [comment]
Sorry, I misunderstood your suggestion. The suggested changes have been committed.

**Comment by SilasMarvin** [comment]
> Sorry, I misunderstood your suggestion. The suggested changes have been committed.

Don't apologize you are totally fine. I think we are having some issues communicating. If you scroll to the top of the page, you will see I have added some suggestions for changes. You can click commit on those directly, or you can add them yourself. Please verify they work and I will merge the PR. Thank you for your contributions!

**Review by luixiao0 — COMMENTED** [review]
checked, work at my env

**Comment by SilasMarvin** [comment]
Thanks for testing it locally. These are the suggestions I am talking about:

Screenshot 2024-06-12 at 12 14 49 PM

We shouldn't call it `completions_endpoint` as Ollama calls it generate. I liked the defaults you had before.

If you can commit those suggestions and test it, I will merge it!

**Comment by luixiao0** [comment]
Is github not working as intended? i cannot see them on my side, nor my mailbox, i will make the change shown in the screenshot
image

> We shouldn't call it completions_endpoint as Ollama calls it generate. I liked the defaults you had before.

i will revert them at next commit

**Comment by SilasMarvin** [comment]
> Is github not working as intended? i cannot see them on my side, nor my mailbox, i will make the change shown in your screenshot image
> 
> > I liked the defaults you had before.
> 
> i will revert them at next commit
> 
> `suggested by gpt-4o: try "submitreview"`

Oh super strange. I have attached the two other suggestions that I made. 

Screenshot 2024-06-12 at 12 38 12 PM

Screenshot 2024-06-12 at 12 38 16 PM

**Comment by luixiao0** [comment]
> > Is github not working as intended? i cannot see them on my side, nor my mailbox, i will make the change shown in your screenshot image
> > > I liked the defaults you had before.
> > 
> > 
> > i will revert them at next commit
> > `suggested by gpt-4o: try "submitreview"`
> 
> Oh super strange. I have attached the two other suggestions that I made.
> 
> Screenshot 2024-06-12 at 12 38 12 PM Screenshot 2024-06-12 at 12 38 16 PM

I've addressed the suggested modifications and it's ready for your feedback

**Comment by SilasMarvin** [comment]
Looks pretty good! 

You should be able to change:
```
.post(self
                .configuration
                .generate_endpoint
                .as_ref()
                .unwrap_or(&"http://localhost:11434/api/generate".to_string())
```

To:
```
.post(self.configuration.generate_endpoint.as_deref().unwrap_or("http://localhost:11434/api/generate"))
```

**Comment by luixiao0** [comment]
my bad, it's done

**Comment by SilasMarvin** [comment]
No worries! Awesome work, I'm going to test locally and merge it tonight!

**Pull request merged**
